matrix:
  include:
  - os: osx
    language: objective-c
    sudo: false
    osx_image: xcode7.3
env:
  global:
  - PROJECT_MOBILE=Example/ios/Example
before_install:
- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew update ; fi
install:
- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew reinstall watchman  ; fi
- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then mkdir -p /Users/travis/build/reading/.nvm
  ; fi
- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then export NVM_DIR="/Users/travis/build/reading/.nvm"
  ; fi
- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew install nvm ; fi
- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then source $(brew --prefix nvm)/nvm.sh ; fi
- nvm install 5
- npm config set spin=false
- npm config set progress=false
- cd Example
- travis_wait npm install
- cd ../

script:
- npm test
- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then xcodebuild -project $PROJECT_MOBILE.xcodeproj
  -sdk iphonesimulator9.3 -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO clean build ; fi